// Module2_FrontEndDev/Gopika_R/hands_on_8/src/App.vue
<template>
  <div class="app-wrapper">
    <Header />
    <main class="main-content">
      <RouterView />
    </main>
    <footer class="site-footer">
      <p>© 2026 Student Portal | All Rights Reserved</p>
    </footer>
  </div>
</template>

<script setup>
import { RouterView } from 'vue-router';
import Header from './components/Header.vue';
</script>

// Module2_FrontEndDev/Gopika_R/hands_on_7/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { HeaderComponent } from './components/header/header.component';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, HeaderComponent],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'hands_on_7';
}

<div class="app-wrapper">
  <app-header></app-header>
  
  <main class="main-content">
    <router-outlet></router-outlet>
  </main>
  
  <footer class="site-footer">
    <p>© 2026 Student Portal | All Rights Reserved</p>
  </footer>
</div>
