// Module2_FrontEndDev/Gopika_R/hands_on_6/src/App.jsx
import React from 'react';
import { Routes, Route } from 'react-router-dom';
import Header from './components/Header';
import Footer from './components/Footer';
import HomePage from './pages/HomePage';
import CoursesPage from './pages/CoursesPage';
import ProfilePage from './pages/ProfilePage';
import CourseDetailPage from './pages/CourseDetailPage';

export default function App() {
    return (
        <div className="app-wrapper">
            {/* Nav Header is rendered on all pages */}
            <Header siteName="Student Portal" />

            <main className="main-content">
                <Routes>
                    <Route path="/" element={<HomePage />} />
                    <Route path="/courses" element={<CoursesPage />} />
                    <Route path="/profile" element={<ProfilePage />} />
                    <Route path="/courses/:courseId" element={<CourseDetailPage />} />
                </Routes>
            </main>

            {/* Footer is rendered on all pages */}
            <Footer />
        </div>
    );
}

// Module2_FrontEndDev/Gopika_R/hands_on_8/src/App.vue
<template>
  <div class="app-wrapper">
    <Header />
    <main class="main-content">
      <RouterView />
    </main>
    <footer class="site-footer">
      <p>© 2026 Student Portal | All Rights Reserved</p>
    </footer>
  </div>
</template>

<script setup>
import { RouterView } from 'vue-router';
import Header from './components/Header.vue';
</script>
