// Module2_FrontEndDev/Gopika_R/hands_on_6/src/components/CourseCard.jsx
import React from 'react';
import { Link } from 'react-router-dom';

export default function CourseCard({ id, name, code, credits, grade, onEnroll, isEnrolled }) {
    return (
        <article className={`course-card ${isEnrolled ? 'enrolled' : ''}`}>
            <h3>{name}</h3>
            <p>Course Code: <strong>{code}</strong></p>
            <div className="card-meta">
                <span className="credits-tag">Credits: {credits}</span>
                <span className="grade-tag">Grade: {grade}</span>
            </div>
            
            <div className="card-actions" style={{ display: 'flex', gap: '10px', marginTop: 'auto' }}>
                <button 
                    onClick={(e) => {
                        e.stopPropagation();
                        onEnroll(id);
                    }} 
                    disabled={isEnrolled}
                    className={`enroll-btn ${isEnrolled ? 'btn-disabled' : 'btn-enroll'}`}
                    style={{ flex: 1 }}
                >
                    {isEnrolled ? '✓ Enrolled' : 'Enroll'}
                </button>
                <Link 
                    to={`/courses/${id}`} 
                    className="btn-secondary btn-small" 
                    style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', textDecoration: 'none', textAlign: 'center', fontSize: '13px', padding: '6px 12px' }}
                >
                    Details
                </Link>
            </div>
        </article>
    );
}

// Module2_FrontEndDev/Gopika_R/hands_on_8/src/components/CourseCard.vue
<template>
  <article class="course-card" :class="{ enrolled: isEnrolled }">
    <h3>{{ course.name }}</h3>
    <p>Course Code: <strong>{{ course.code }}</strong></p>
    <div class="card-meta">
      <span class="credits-tag">Credits: {{ course.credits }}</span>
      <span class="grade-tag">Grade: {{ course.grade }}</span>
    </div>
    <div class="card-actions">
      <button
        :disabled="isEnrolled"
        :class="isEnrolled ? 'btn-disabled' : 'btn-enroll'"
        class="enroll-btn"
        @click="$emit('enroll', course.id)"
      >
        {{ isEnrolled ? '✓ Enrolled' : 'Enroll' }}
      </button>
      <RouterLink :to="`/courses/${course.id}`" class="btn-details">Details</RouterLink>
    </div>
  </article>
</template>

<script setup>
import { RouterLink } from 'vue-router';

defineProps({
  course: { type: Object, required: true },
  isEnrolled: { type: Boolean, default: false }
});

defineEmits(['enroll']);
</script>
