// Module2_FrontEndDev/Gopika_R/hands_on_7/src/app/components/header/header.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [RouterLink, RouterLinkActive],
  templateUrl: './header.component.html',
  styleUrls: []
})
export class HeaderComponent {
  siteName = 'Student Portal';
}

<header class="site-header">
    <h2 class="logo">
        <a [routerLink]="['/']" style="color: inherit; text-decoration: none;">{{ siteName }}</a>
    </h2>
    <nav class="nav-menu">
        <ul>
            <li>
                <a [routerLink]="['/']" routerLinkActive="active" [routerLinkActiveOptions]="{exact: true}">Courses</a>
            </li>
            <li>
                <a [routerLink]="['/profile']" routerLinkActive="active">Profile</a>
            </li>
        </ul>
    </nav>
</header>

// Module2_FrontEndDev/Gopika_R/hands_on_8/src/components/Header.vue
<template>
  <header class="site-header">
    <h2 class="logo">
      <RouterLink to="/">Student Portal</RouterLink>
    </h2>
    <nav class="nav-menu">
      <ul>
        <li><RouterLink to="/" active-class="active" exact-active-class="active">Courses</RouterLink></li>
        <li><RouterLink to="/profile" active-class="active">Profile</RouterLink></li>
      </ul>
    </nav>
    <div class="enroll-badge">
      <span>📚 Enrolled: <strong>{{ enrollmentStore.enrolledCount }}</strong></span>
    </div>
  </header>
</template>

<script setup>
import { RouterLink } from 'vue-router';
import { useEnrollmentStore } from '../stores/enrollment';

const enrollmentStore = useEnrollmentStore();
</script>
