// Module2_FrontEndDev/Gopika_R/hands_on_8/src/components/Header.vue
<template>
  <header class="site-header">
    <h2 class="logo">
      <RouterLink to="/">Student Portal</RouterLink>
    </h2>
    <nav class="nav-menu">
      <ul>
        <li><RouterLink to="/" active-class="active" exact-active-class="active">Courses</RouterLink></li>
        <li><RouterLink to="/profile" active-class="active">Profile</RouterLink></li>
      </ul>
    </nav>
    <div class="enroll-badge">
      <span>📚 Enrolled: <strong>{{ enrollmentStore.enrolledCount }}</strong></span>
    </div>
  </header>
</template>

<script setup>
import { RouterLink } from 'vue-router';
import { useEnrollmentStore } from '../stores/enrollment';

const enrollmentStore = useEnrollmentStore();
</script>

// Module2_FrontEndDev/Gopika_R/hands_on_6/src/components/Header.jsx
import React from 'react';
import { Link, useLocation } from 'react-router-dom';
import { useSelector } from 'react-redux';

export default function Header({ siteName }) {
    const location = useLocation();
    const enrolledCourses = useSelector(state => state.enrollment.enrolledCourses);

    return (
        <header className="site-header">
            <h2 className="logo">
                <Link to="/" style={{ color: 'inherit', textDecoration: 'none' }}>
                    {siteName || "Student Portal"}
                </Link>
            </h2>
            <nav className="nav-menu">
                <ul>
                    <li>
                        <Link to="/" className={location.pathname === '/' ? 'active' : ''}>Home</Link>
                    </li>
                    <li>
                        <Link to="/courses" className={location.pathname.startsWith('/courses') ? 'active' : ''}>Courses</Link>
                    </li>
                    <li>
                        <Link to="/profile" className={location.pathname === '/profile' ? 'active' : ''}>Profile</Link>
                    </li>
                </ul>
            </nav>
            <div className="enroll-badge">
                <span>📚 Enrolled: <strong>{enrolledCourses.length}</strong></span>
            </div>
        </header>
    );
}
