// Module2_FrontEndDev/Gopika_R/hands_on_8/src/components/CourseCard.vue
<template>
  <article class="course-card" :class="{ enrolled: isEnrolled }">
    <h3>{{ course.name }}</h3>
    <p>Course Code: <strong>{{ course.code }}</strong></p>
    <div class="card-meta">
      <span class="credits-tag">Credits: {{ course.credits }}</span>
      <span class="grade-tag">Grade: {{ course.grade }}</span>
    </div>
    <div class="card-actions">
      <button
        :disabled="isEnrolled"
        :class="isEnrolled ? 'btn-disabled' : 'btn-enroll'"
        class="enroll-btn"
        @click="$emit('enroll', course.id)"
      >
        {{ isEnrolled ? '✓ Enrolled' : 'Enroll' }}
      </button>
      <RouterLink :to="`/courses/${course.id}`" class="btn-details">Details</RouterLink>
    </div>
  </article>
</template>

<script setup>
import { RouterLink } from 'vue-router';

defineProps({
  course: { type: Object, required: true },
  isEnrolled: { type: Boolean, default: false }
});

defineEmits(['enroll']);
</script>

// Module2_FrontEndDev/Gopika_R/hands_on_5/src/components/CourseCard.jsx
import React from 'react';

export default function CourseCard({ id, name, code, credits, grade, onEnroll, isEnrolled }) {
    return (
        <article className={`course-card ${isEnrolled ? 'enrolled' : ''}`}>
            <h3>{name}</h3>
            <p>Course Code: <strong>{code}</strong></p>
            <div className="card-meta">
                <span className="credits-tag">Credits: {credits}</span>
                <span className="grade-tag">Grade: {grade}</span>
            </div>
            <button 
                onClick={() => onEnroll(id)} 
                disabled={isEnrolled}
                className={`enroll-btn ${isEnrolled ? 'btn-disabled' : 'btn-enroll'}`}
            >
                {isEnrolled ? '✓ Enrolled' : 'Enroll Course'}
            </button>
        </article>
    );
}
