// Module2_FrontEndDev/Gopika_R/hands_on_8/src/components/Header.vue
<template>
  <header class="site-header">
    <h2 class="logo">
      <RouterLink to="/">Student Portal</RouterLink>
    </h2>
    <nav class="nav-menu">
      <ul>
        <li><RouterLink to="/" active-class="active" exact-active-class="active">Courses</RouterLink></li>
        <li><RouterLink to="/profile" active-class="active">Profile</RouterLink></li>
      </ul>
    </nav>
    <div class="enroll-badge">
      <span>📚 Enrolled: <strong>{{ enrollmentStore.enrolledCount }}</strong></span>
    </div>
  </header>
</template>

<script setup>
import { RouterLink } from 'vue-router';
import { useEnrollmentStore } from '../stores/enrollment';

const enrollmentStore = useEnrollmentStore();
</script>

// Module2_FrontEndDev/Gopika_R/hands_on_5/src/components/Header.jsx
import React from 'react';

export default function Header({ siteName, enrolledCount }) {
    return (
        <header className="site-header">
            <h2 className="logo">{siteName || "Student Portal"}</h2>
            <nav className="nav-menu">
                <ul>
                    <li><a href="#" className="active">Home</a></li>
                    <li><a href="#">Courses</a></li>
                    <li><a href="#">Profile</a></li>
                    <li><a href="#">Grades</a></li>
                </ul>
            </nav>
            <div className="enroll-badge">
                <span>📚 Enrolled: <strong>{enrolledCount}</strong></span>
            </div>
        </header>
    );
}
