// Module2_FrontEndDev/Gopika_R/hands_on_7/src/app/components/student-profile/student-profile.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormGroup, FormControl, Validators } from '@angular/forms';

@Component({
  selector: 'app-student-profile',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  templateUrl: './student-profile.component.html',
  styles: []
})
export class StudentProfileComponent implements OnInit {
  profileForm!: FormGroup;

  ngOnInit(): void {
    this.profileForm = new FormGroup({
      name: new FormControl('Gopika R', [Validators.required]),
      email: new FormControl('gopika.r@example.com', [Validators.required, Validators.email]),
      semester: new FormControl('6', [
        Validators.required, 
        Validators.min(1), 
        Validators.max(8)
      ])
    });
  }

  onSubmit(): void {
    if (this.profileForm.valid) {
      console.log('Form Submitted successfully!', this.profileForm.value);
    }
  }

  // Getters for easy template checks
  get name() { return this.profileForm.get('name'); }
  get email() { return this.profileForm.get('email'); }
  get semester() { return this.profileForm.get('semester'); }
}

<section class="profile-section">
    <h2>Student Profile</h2>
    <div class="profile-container">
        <!-- Reactive Form -->
        <form class="profile-form" [formGroup]="profileForm" (ngSubmit)="onSubmit()">
            <div class="form-group">
                <label htmlFor="name-input">Full Name</label>
                <input 
                    type="text" 
                    id="name-input"
                    formControlName="name"
                    placeholder="Enter full name"
                />
                <div *ngIf="name?.touched && name?.invalid" class="validation-error" style="color: #e71d36; font-size: 13px; font-weight: 600; margin-top: 4px;">
                    <span *ngIf="name?.errors?.['required']">Name is required</span>
                </div>
            </div>
            
            <div class="form-group">
                <label htmlFor="email-input">Email Address</label>
                <input 
                    type="email" 
                    id="email-input"
                    formControlName="email"
                    placeholder="Enter email address"
                />
                <div *ngIf="email?.touched && email?.invalid" class="validation-error" style="color: #e71d36; font-size: 13px; font-weight: 600; margin-top: 4px;">
                    <span *ngIf="email?.errors?.['required']">Email is required</span>
                    <span *ngIf="email?.errors?.['email']">Enter a valid email</span>
                </div>
            </div>
            
            <div class="form-group">
                <label htmlFor="semester-input">Current Semester</label>
                <input 
                    type="number" 
                    id="semester-input"
                    formControlName="semester"
                    placeholder="Semester"
                />
                <div *ngIf="semester?.touched && semester?.invalid" class="validation-error" style="color: #e71d36; font-size: 13px; font-weight: 600; margin-top: 4px;">
                    <span *ngIf="semester?.errors?.['required']">Semester is required</span>
                    <span *ngIf="semester?.errors?.['min'] || semester?.errors?.['max']">Semester must be between 1 and 8</span>
                </div>
            </div>

            <button 
                type="submit" 
                class="btn-primary" 
                [disabled]="profileForm.invalid"
                style="margin-top: 15px; width: 100%;"
            >
                Submit Form
            </button>
        </form>

        <!-- Live Profile Card View -->
        <div class="profile-card-preview">
            <div class="avatar-placeholder">
                {{ profileForm.value.name ? profileForm.value.name.charAt(0).toUpperCase() : 'S' }}
            </div>
            <div class="preview-details">
                <h3>{{ profileForm.value.name || "Student Name" }}</h3>
                <p class="email-text">📧 {{ profileForm.value.email || "student@example.com" }}</p>
                <p class="sem-text">Semester <strong>{{ profileForm.value.semester || "-" }}</strong></p>
            </div>
        </div>
    </div>
</section>

// Module2_FrontEndDev/Gopika_R/hands_on_5/src/components/StudentProfile.jsx
import React, { useState } from 'react';

export default function StudentProfile() {
    const [profile, setProfile] = useState({
        name: 'Gopika R',
        email: 'gopika.r@example.com',
        semester: '6'
    });

    const handleChange = (e) => {
        const { name, value } = e.target;
        setProfile(prev => ({
            ...prev,
            [name]: value
        }));
    };

    return (
        <section className="profile-section">
            <h2>Student Profile</h2>
            <div className="profile-container">
                {/* Form to update state */}
                <form className="profile-form" onSubmit={(e) => e.preventDefault()}>
                    <div className="form-group">
                        <label htmlFor="name-input">Full Name</label>
                        <input 
                            type="text" 
                            id="name-input"
                            name="name" 
                            value={profile.name} 
                            onChange={handleChange} 
                            placeholder="Enter full name"
                        />
                    </div>
                    <div className="form-group">
                        <label htmlFor="email-input">Email Address</label>
                        <input 
                            type="email" 
                            id="email-input"
                            name="email" 
                            value={profile.email} 
                            onChange={handleChange} 
                            placeholder="Enter email address"
                        />
                    </div>
                    <div className="form-group">
                        <label htmlFor="semester-input">Current Semester</label>
                        <input 
                            type="number" 
                            id="semester-input"
                            name="semester" 
                            value={profile.semester} 
                            onChange={handleChange} 
                            min="1" 
                            max="8" 
                            placeholder="Semester"
                        />
                    </div>
                </form>

                {/* Profile Live Card View */}
                <div className="profile-card-preview">
                    <div className="avatar-placeholder">
                        {profile.name ? profile.name.split(' ').map(n => n[0]).join('').toUpperCase() : 'S'}
                    </div>
                    <div className="preview-details">
                        <h3>{profile.name || "Student Name"}</h3>
                        <p className="email-text">📧 {profile.email || "student@example.com"}</p>
                        <p className="sem-text">Semester <strong>{profile.semester || "-"}</strong></p>
                    </div>
                </div>
            </div>
        </section>
    );
}
