// Module2_FrontEndDev/Gopika_R/hands_on_5/src/components/CourseCard.jsx
import React from 'react';

export default function CourseCard({ id, name, code, credits, grade, onEnroll, isEnrolled }) {
    return (
        <article className={`course-card ${isEnrolled ? 'enrolled' : ''}`}>
            <h3>{name}</h3>
            <p>Course Code: <strong>{code}</strong></p>
            <div className="card-meta">
                <span className="credits-tag">Credits: {credits}</span>
                <span className="grade-tag">Grade: {grade}</span>
            </div>
            <button 
                onClick={() => onEnroll(id)} 
                disabled={isEnrolled}
                className={`enroll-btn ${isEnrolled ? 'btn-disabled' : 'btn-enroll'}`}
            >
                {isEnrolled ? '✓ Enrolled' : 'Enroll Course'}
            </button>
        </article>
    );
}

// Module2_FrontEndDev/Gopika_R/hands_on_7/src/app/components/course-card/course-card.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-course-card',
  standalone: true,
  imports: [],
  templateUrl: './course-card.component.html',
  styles: []
})
export class CourseCardComponent {
  @Input() name!: string;
  @Input() code!: string;
  @Input() credits!: number;
  @Input() grade!: string;
}

<article class="course-card">
    <h3>{{ name }}</h3>
    <p>Course Code: <strong>{{ code }}</strong></p>
    <div class="card-meta">
        <span class="credits-tag">Credits: {{ credits }}</span>
        <span class="grade-tag">Grade: {{ grade }}</span>
    </div>
</article>
